### ISSUE TITLE
Unable to start uber jar with Neo4j Migrations on Spring Boot 3.2.0

### ISSUE THREAD

**Issue by alexanoid** [michael-simons/neo4j-migrations#1153]
I'm trying to migrate to new Spring Boot 3.2.0

I use neo4j-migrations-spring-boot-starter:2.7.0

I created an uber jar and trying to start the application with java -jar ui-0.0.1.jar 

It fails with the following exception:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'neo4jMigrationsInitializer' defined in class path resource [ac/simons/neo4j/migrations/springframework/boot/autoconfigure/MigrationsAutoConfiguration.class]: java.io.FileNotFoundException: JAR entry BOOT-INF/lib/domain-0.0.1.jar!/neo4j/migrations/V0001__indexes.cypher not found in /srv/api/ui-0.0.1.jar
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1775) ~[spring-beans-6.1.1.jar!/:6.1.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601) ~[spring-beans-6.1.1.jar!/:6.1.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523) ~[spring-beans-6.1.1.jar!/:6.1.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.1.jar!/:6.1.1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.1.jar!/:6.1.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.1.jar!/:6.1.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.1.jar!/:6.1.1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.1.1.jar!/:6.1.1]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:946) ~[spring-context-6.1.1.jar!/:6.1.1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616) ~[spring-context-6.1.1.jar!/:6.1.1]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.0.jar!/:3.2.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:753) ~[spring-boot-3.2.0.jar!/:3.2.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:455) ~[spring-boot-3.2.0.jar!/:3.2.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-3.2.0.jar!/:3.2.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342) ~[spring-boot-3.2.0.jar!/:3.2.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331) ~[spring-boot-3.2.0.jar!/:3.2.0]
	at com.example.ui.Application.main(Application.java:31) ~[!/:0.0.1]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[ui-0.0.1.jar:0.0.1]
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[ui-0.0.1.jar:0.0.1]
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[ui-0.0.1.jar:0.0.1]
Caused by: java.io.UncheckedIOException: java.io.FileNotFoundException: JAR entry BOOT-INF/lib/domain-0.0.1.jar!/neo4j/migrations/V0001__indexes.cypher not found in /srv/api/ui-0.0.1.jar
	at ac.simons.neo4j.migrations.core.CypherResource.lambda$of$0(CypherResource.java:57) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.DefaultCypherResource.readStatements(DefaultCypherResource.java:178) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.DefaultCypherResource.getStatements(DefaultCypherResource.java:161) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.DefaultCypherResource.getStatements(DefaultCypherResource.java:148) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.DefaultCypherResource.getSingleLineComments(DefaultCypherResource.java:227) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.Precondition.in(Precondition.java:109) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.CypherBasedMigration.getPreconditions(CypherBasedMigration.java:115) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.DiscoveryService.lambda$computeAlternativeChecksums$2(DiscoveryService.java:97) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at ac.simons.neo4j.migrations.core.DiscoveryService.computeAlternativeChecksums(DiscoveryService.java:96) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.DiscoveryService.findMigrations(DiscoveryService.java:69) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.Migrations.getMigrations(Migrations.java:115) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.Migrations.lambda$apply$3(Migrations.java:226) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.Migrations.executeWithinLock(Migrations.java:608) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.core.Migrations.apply(Migrations.java:222) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	at ac.simons.neo4j.migrations.springframework.boot.autoconfigure.MigrationsInitializer.afterPropertiesSet(MigrationsInitializer.java:45) ~[neo4j-migrations-spring-boot-autoconfigure-2.7.0.jar!/:2.7.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1822) ~[spring-beans-6.1.1.jar!/:6.1.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1771) ~[spring-beans-6.1.1.jar!/:6.1.1]
	... 23 common frames omitted
Caused by: java.io.FileNotFoundException: JAR entry BOOT-INF/lib/domain-0.0.1.jar!/neo4j/migrations/V0001__indexes.cypher not found in /srv/api/ui-0.0.1.jar
	at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.throwFileNotFound(JarUrlConnection.java:331) ~[ui-0.0.1.jar:0.0.1]
	at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.getJarEntry(JarUrlConnection.java:319) ~[ui-0.0.1.jar:0.0.1]
	at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.connect(JarUrlConnection.java:290) ~[ui-0.0.1.jar:0.0.1]
	at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.getInputStream(JarUrlConnection.java:195) ~[ui-0.0.1.jar:0.0.1]
	at java.base/java.net.URL.openStream(URL.java:1161) ~[na:na]
	at ac.simons.neo4j.migrations.core.CypherResource.lambda$of$0(CypherResource.java:55) ~[neo4j-migrations-2.7.0.jar!/:2.7.0]
	... 40 common frames omitted
```

With Spring Boot 3.1.5 everything is working fine.

My application structure:

```
domain - submodule where Neo4j migration files are located
ui - submodule - I run this uber jar. In uber jar it contains domain.jar in libs folder
pom.xm
```

Somehow, it doesn't recognize the migration files in the domain submodule when using Spring Boot 3.2.0. The same configuration on Spring Boot 3.1.5 works fine. Additionally, it starts well with SB 3.2.0 from IDEA via the Application class. It seems that it only encounters an issue when starting from the uber jar.

**Comment by alexanoid** [comment]
Hi! Thanks for your response! Are you using a single-module uber jar in your tests, or is it a multi-module setup? I have two modules, 'domain' and 'ui.' My migrations are stored inside the 'domain' module, but I run the 'ui.jar,' which internally depends on 'domain.

**Comment by michael-simons** [comment]
Nope and I can actually reproduce it.

**Comment by michael-simons** [comment]
There's a big change in Boot 3.2 that is not covered by the class graph class scanner (which we are using to discover resources)

See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support

If you set the loader to `CLASSIC` it will work

```xml
 <configuration>
            <loaderImplementation>CLASSIC</loaderImplementation>
          </configuration>
```

**Comment by alexanoid** [comment]
The following works:

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                
                <configuration>
                    <wait>500</wait>
                    <maxAttempts>240</maxAttempts>
                    <loaderImplementation>CLASSIC</loaderImplementation>
                </configuration>
            </plugin>

Thank you very much !!!

**Comment by michael-simons** [comment]
My pleasure, Alex, and likewise.

@all-contributors please add @alexanoid for bug

**Comment by michael-simons** [comment]
I added a fix so that the workaround of falling back to the "classic" thing will be superfluous next release.
