### ISSUE TITLE
Latest 1.5.5 exception on JDK8

### ISSUE THREAD

**Issue by mattborderux** [michael-simons/neo4j-migrations#490]
This is running in a Docker container with `8u212-jdk-alpine`.   This problem did not exist in 1.5.4

```
Performing migration
neo4j-migrations    | [jbang] Resolving dependencies...
neo4j-migrations    | [jbang] eu.michael-simons.neo4j:neo4j-migrations-cli:jar:1.5.5
neo4j-migrations    | Done
neo4j-migrations    | [jbang] Dependencies resolved
neo4j-migrations    | [jbang] Building jar...
neo4j-migrations    | Exception in thread "main" java.lang.UnsupportedClassVersionError: org/graalvm/nativeimage/ImageInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
neo4j-migrations    | 	at java.lang.ClassLoader.defineClass1(Native Method)
neo4j-migrations    | 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
neo4j-migrations    | 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
neo4j-migrations    | 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
neo4j-migrations    | 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
neo4j-migrations    | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
neo4j-migrations    | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
neo4j-migrations    | 	at java.security.AccessController.doPrivileged(Native Method)
neo4j-migrations    | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
neo4j-migrations    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
neo4j-migrations    | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
neo4j-migrations    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
neo4j-migrations    | 	at ac.simons.neo4j.migrations.cli.MigrationsCli.getConfig(MigrationsCli.java:222)
neo4j-migrations    | 	at ac.simons.neo4j.migrations.cli.ConnectedCommand.call(ConnectedCommand.java:58)
neo4j-migrations    | 	at ac.simons.neo4j.migrations.cli.ConnectedCommand.call(ConnectedCommand.java:40)
neo4j-migrations    | 	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
neo4j-migrations    | 	at picocli.CommandLine.access$1300(CommandLine.java:145)
neo4j-migrations    | 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
neo4j-migrations    | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
neo4j-migrations    | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
neo4j-migrations    | 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
neo4j-migrations    | 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
neo4j-migrations    | 	at picocli.CommandLine.execute(CommandLine.java:2078)
neo4j-migrations    | 	at ac.simons.neo4j.migrations.cli.MigrationsCli.main(MigrationsCli.java:110)
neo4j-migrations    | 	at neo4j_migrations.main(neo4j_migrations.java:8)
```

**Comment by michael-simons** [comment]
While a fix is on the way, an easy workaround is to run the Jbang script in your container with `//JAVA 11`.
